### PR TITLE
ci: fix tarpaulin

### PR DESCRIPTION
**Pull request by tobealive**

### CODE REVIEW

**Comment by tobealive** [comment]
Thanks for the recent attempt @kevinmatthes .

Inspired on your changes I'll attempt to fix this here. If this this succeeds and you are free for it you can sign it off then 🙂👍.

**Review by kevinmatthes — APPROVED** [review]
Thank you for your work, @tobealive!  I am honestly surprised that the solution was as simple as these few changes.

**Comment by tobealive** [comment]
Of course this didn't fix tarpaulin here, just the coverage workflow :P sub-optimal merge message, it was getting late.

I usually wanted to include limiting the coverage CI in this PR, but forgot this as well.
```yml
    paths: ["**/*.rs", "**/*.toml", "**/*.lock", "**/tarpaulin.yml"]
```

I thought those should be all the cases. What's your experience with this @kevinmatthes ?

**Comment by kevinmatthes** [comment]
@tobealive

These are indeed all major cases.  Regarding the notation, I previously used `src/` as prefix in another repository and thus had to enumerate all cases of sub-directory configurations.  But I assume that this notation should work, as well.

**Comment by tobealive** [comment]
Thanks for having a look!

Yep, it's the notation used to limit the paths in `ci.yml` so we should be good.

**Pull request merged**
