### PR TITLE
Add nix flake

### PR DESCRIPTION
**Pull request by Sciencentistguy**
Add flake., to allow installation via Nix.

This PR also un-ignores `Cargo.lock`, as this is a binary crate.

### CODE REVIEW

**Review by tobealive — APPROVED** [review]
I must admit that I have limit knowledge on nix. From what I can tell it looks good, thank you 👍️

I'm on my phone currently. I'll come back to this soon.

**Comment by tobealive** [comment]
I'm splitting this PR up as I'd classify its contents as separate topics. Thanks for your contribution ❤️!

**Comment by Sciencentistguy** [comment]
I'm not the biggest fan of you re-authoring my commits, tbh

**Comment by tobealive** [comment]
Yes, I'm also denied to make changes on the branch and unfortunately currently stuck with a bad internet connection.
I'm merging it now from a copied branch containing your commtis to get this done.

One thing I addintionally prefered was the lock file to be generated on a trusted machine, but in the end I also could have generated it locally and checked the diffs with yours, so it would be fine. Anyway, in the end the maintainers of a repository should decied how changes get merged. Thanks for your understanding.

**Comment by tobealive** [comment]
need to do a cleanup and rebase that your commits appear soory about this. I'm fixing this

**Comment by Sciencentistguy** [comment]
Thank you :slightly_smiling_face:

**Pull request closed without merging**
